server:
  port: 7801
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: twoxfour
    url: jdbc:mysql://localhost:3306/springcloud
    driver-class-name: com.mysql.jdbc.Driver